baseURL = 'https://colinalley.com/'
locale = 'en-us'
title = 'colin_alley'
theme = 'shibui'

[menu]
  [[menu.main]]
    name = "posts"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    name = "tags"
    url = "/tags/"
    weight = 2
  [[menu.main]]
    name = "books"
    url = "https://www.goodreads.com/colinalley"
    weight = 3
  [[menu.main]]
    name = "movies"
    url = "https://boxd.it/lpKFp"
    weight = 4

[caches]
  [caches.images]
    dir = ':cacheDir/images'
